apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio-tenant

resources:
- namespace.yaml
- minio-local-storageclass.yaml
- pv-slave01.yaml
- pv-slave02.yaml
- storage-user.yaml
- storage-configuration-v3.yaml
- tenant.yaml
- ingress/minio-ingress.yaml
# - node-port/minio-console-nodeport.yaml
# - node-port/minio-nodeport.yaml