apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration-v3
  namespace: minio-tenant
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="admin"
    export MINIO_ROOT_PASSWORD="4d494e494f5f524f4f545f50415353574f5244"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"

    # --- Kafka Notification Configuration ---
    # export MINIO_NOTIFY_KAFKA_ENABLE_EVENTLOCAL="on"
    # export MINIO_NOTIFY_KAFKA_BROKERS_EVENTLOCAL="118.70.52.237:9000"
    # export MINIO_NOTIFY_KAFKA_TOPIC_EVENTLOCAL="minio-datalens"
    # export MINIO_NOTIFY_KAFKA_SASL_USERNAME_EVENTLOCAL=""
    # export MINIO_NOTIFY_KAFKA_SASL_PASSWORD_EVENTLOCAL=""
    # export MINIO_NOTIFY_KAFKA_TLS_ENABLE_EVENTLOCAL="off"